name: test
on: push
jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Clone or get my code here
              uses: action/checkout@v3
            - name: Install NodeJS
              uses: action/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test

